name: gpu_env
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- bzip2=1.0.8=h4bc722e_7
- ca-certificates=2024.8.30=hbcca054_0
- cuda-version=11.8=h70ddcb2_3
- cudatoolkit=11.8.0=h4ba93d1_13
- cudnn=8.9.7.29=hbc23b4c_3
- kernel-headers_linux-64=3.10.0=he073ed8_18
- ld_impl_linux-64=2.43=h712a8e2_2
- libffi=3.4.2=h7f98852_5
- libgcc=14.2.0=h77fa898_1
- libgcc-ng=14.2.0=h69a702a_1
- libgomp=14.2.0=h77fa898_1
- libnsl=2.0.1=hd590300_0
- libsqlite=3.46.0=hde9e2c9_0
- libstdcxx=14.2.0=hc0a3c3a_1
- libstdcxx-ng=14.2.0=h4852527_1
- libuuid=2.38.1=h0b41bf4_0
- libzlib=1.3.1=hb9d3cd8_2
- ncurses=6.5=he02047a_1
- openssl=1.1.1w=hd590300_0
- pip=24.3.1=pyh8b19718_0
- python=3.8.15=h257c98d_0_cpython
- readline=8.2=h8228510_1
- setuptools=75.3.0=pyhd8ed1ab_0
- sqlite=3.46.0=h6d4b2fc_0
- sysroot_linux-64=2.17=h4a8ded7_18
- tk=8.6.13=noxft_h4845f30_101
- tzdata=2024b=hc8b5060_0
- wheel=0.45.1=pyhd8ed1ab_0
- xz=5.2.6=h166bdaf_0
- zlib=1.3.1=hb9d3cd8_2

